services:

  profanex_test_runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        INSTALL_DEV_DEPENDENCIES: "true"
    image: profanex_test_runner
    pull_policy: never
    container_name: profanex_test_runner
    environment:
      - ENV_TYPE=docker_dev
    volumes:
      - ${PWD}/pyproject.toml:/src/pyproject.toml
      - ${PWD}/uv.lock:/src/uv.lock
      - ${PWD}/profanex/:/src/profanex
      - ${PWD}/fixtures/:/src/fixtures
      - ${PWD}/tests/:/src/tests
      - ${PWD}/src/:/src/src
      - ${PWD}/crates/:/src/crates
      - ${PWD}/Cargo.toml:/src/Cargo.toml
      - ${PWD}/Cargo.lock:/src/Cargo.lock
      - ${PWD}/rust-toolchain.toml:/src/rust-toolchain.toml
    working_dir: /src
    command: uv run pytest
